query_expansion:
  model_id: anthropic.claude-3-haiku-20240307-v1:0
  system_message: Respond valid json format.
  assistant_message: "{"
  args:
    anthropic_version: bedrock-2023-05-31
    max_tokens: 1000
    temperature: 0
    stop_sequences: ["</output>"]
